spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eazy
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    drop-first: true
    labels: update
    change-log: classpath:liquibase/changelog.xml