spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eazy
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create